name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit
    - name: Run Bandit security scan
      run: |
        bandit -r pyzcap -f json -o bandit-results.json
    - name: Upload scan results
      uses: actions/upload-artifact@v3
      with:
        name: bandit-results
        path: bandit-results.json 